name: create table for mysql

# 控制工作流触发的事件
on:
  workflow_dispatch: # 手动触发工作流

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      # 检出代码
      #- uses: actions/checkout@v2

      # 设置运行环境
      - name: Setup Environment
        run: |
          make grant_priv

      # 运行建表脚本
      - name: Run create table  script
        run: ./create_table -mysqlPwd ${{secrets.MYSQLPWD}} -moPwd ${{secrets.MOPWD}}
