name: Scheduled Task

on:
  schedule:
    # 每小时运行一次工作流程
    - cron: '30 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run task
      run: echo "This task runs every hour."
